/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/ContainerManagement': RouteRecordInfo<'/ContainerManagement', '/ContainerManagement', Record<never, never>, Record<never, never>>,
    '/IPConfiguration': RouteRecordInfo<'/IPConfiguration', '/IPConfiguration', Record<never, never>, Record<never, never>>,
    '/ReverseProxyConfiguration': RouteRecordInfo<'/ReverseProxyConfiguration', '/ReverseProxyConfiguration', Record<never, never>, Record<never, never>>,
    '/SystemMonitoring': RouteRecordInfo<'/SystemMonitoring', '/SystemMonitoring', Record<never, never>, Record<never, never>>,
  }
}
